Avus_02/Controllers/HabitacionesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Text;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Avus_02.Model;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Hosting.Internal;

namespace Avus_02.Controllers
{
    public class HabitacionesController : Controller
    {
        private readonly AvusContext _context;
        private readonly IHostingEnvironment hostingEnvironment;

        public HabitacionesController(AvusContext context, IHostingEnvironment environment)
        {
            _context = context;
            hostingEnvironment = environment;
        }

        // GET: Habitaciones
        public async Task<IActionResult> Index()
        {
            var avusContext = _context.Habitacion.Include(h => h.IdAbueloNavigation);
            return View(await avusContext.ToListAsync());
        }

        // GET: Habitaciones/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var habitacion = await _context.Habitacion
                .Include(h => h.IdAbueloNavigation)
                .FirstOrDefaultAsync(m => m.IdHabitacion == id);
            if (habitacion == null)
            {
                return NotFound();
            }

            return View(habitacion);
        }

        // GET: Habitaciones/Create
        public IActionResult Create()
        {
            ViewData["IdAbuelo"] = new SelectList(_context.Abuelo, "IdAbuelo", "IdAbuelo");
            return View();
        }

        // POST: Habitaciones/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdHabitacion,IdAbuelo")] Habitacion habitacion, string Descripcion, string Fumar, string Mascotas, string Invitados, string Wifi, SubirFoto foto)
        {
            //No se puede poner dentro del Bind los valores de los checkboxes porque esto sdevuelven un string 'on' o null.
            if (ModelState.IsValid)
            {
                int intFumar = (Fumar == "on") ? 1 : 0;
                int intMascotas = (Mascotas == "on") ? 1 : 0;
                int intWifi = (Wifi == "on") ? 1 : 0;
                int intInvitados = (Invitados == "on") ? 1 : 0;
                habitacion.Fumar = intFumar;
                habitacion.Mascotas = intMascotas;
                habitacion.Wifi = intWifi;
                habitacion.Invitados = intInvitados;
                habitacion.Disponible = 1;
                habitacion.Descripcion = Descripcion;

                var idAbuelo = HttpContext.Session.GetInt32("id");
                habitacion.IdAbuelo = idAbuelo;
                _context.Add(habitacion);
                await _context.SaveChangesAsync();
                SubirImagenesController.CreateImageRoom(foto, hostingEnvironment, habitacion.IdAbuelo, habitacion.IdHabitacion);
                return RedirectToAction("Habitaciones", "Abuelos");
            }
            ViewData["IdAbuelo"] = new SelectList(_context.Abuelo, "IdAbuelo", "IdAbuelo", habitacion.IdAbuelo);
            return View(habitacion);
        }

        // GET: Habitaciones/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var habitacion = await _context.Habitacion.FindAsync(id);
            if (habitacion == null)
            {
                return NotFound();
            }
            ViewData["IdAbuelo"] = new SelectList(_context.Abuelo, "IdAbuelo", "IdAbuelo", habitacion.IdAbuelo);
            return View(habitacion);
        }

        // POST: Habitaciones/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdHabitacion,Descripcion,Fumar,Wifi,Mascotas,Invitados,Disponible,IdAbuelo")] Habitacion habitacion)
        {
            if (id != habitacion.IdHabitacion)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(habitacion);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!HabitacionExists(habitacion.IdHabitacion))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdAbuelo"] = new SelectList(_context.Abuelo, "IdAbuelo", "IdAbuelo", habitacion.IdAbuelo);
            return View(habitacion);
        }

        // GET: Habitaciones/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var habitacion = await _context.Habitacion
                .Include(h => h.IdAbueloNavigation)
                .FirstOrDefaultAsync(m => m.IdHabitacion == id);
            if (habitacion == null)
            {
                return NotFound();
            }

            return View(habitacion);
        }

        // POST: Habitaciones/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var habitacion = await _context.Habitacion.FindAsync(id);
            _context.Habitacion.Remove(habitacion);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool HabitacionExists(int id)
        {
            return _context.Habitacion.Any(e => e.IdHabitacion == id);
        }

        public IActionResult CrearHabitacion()
        {
            return View();
        }

    }
}

Avus_02/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Avus_02.Models;
using Avus_02.Model;
using Microsoft.AspNetCore.Http;

namespace Avus_02.Controllers
{
    public class LoginController : Controller
    {
        private readonly AvusContext _context;

        public LoginController(AvusContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var tipo = HttpContext.Session.GetString("tipo");
            if (tipo != null) { 
            if (tipo.Equals("abuelo"))
            {
                return RedirectToAction("Solicitudes", "Abuelos");
            }
            if (tipo.Equals("estudiante"))
            {
                return RedirectToAction("Solicitudes", "Estudiantes");
            } }

            return View();
        }



        public IActionResult EstudianteYAbuelo()
        {
            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
        
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
        public IActionResult Logout()
        {
            HttpContext.Session.Clear();
            return RedirectToAction("Index");
        }
        public IActionResult About()
        {
            return View();
        }
        // POST: Abuelos/Search(email)
        [HttpPost]
        public IActionResult SearchEmail(string email, string password)
        {
            if (email == null || password == null)
            {
                return NotFound();
            }
            //Si lo queremos realizar de una manera asyncorna tendriamos que recojer toda la bbdd y crear un bucle, el where no es async.
            //Where buscando por email y password 
            // utilizamos el metodo computesha para encryptarlo en hash y compararlo con nuestra clave hash en nuestra bbdd 
            var abuelo = _context.Abuelo.Where(predicate: s => s.Email.Equals(email) && s.Password.Equals(Encriptar.ComputeSha256Hash(password))).FirstOrDefault();
            var estudiante = _context.Estudiante.Where(predicate: s => s.Email.Equals(email) && s.Password.Equals(Encriptar.ComputeSha256Hash(password))).FirstOrDefault();
            
            if (abuelo != null)
            {
                //Cookie session donde guardamos solo el ID 
                HttpContext.Session.SetInt32("id",abuelo.IdAbuelo);
                HttpContext.Session.SetString("tipo", "abuelo");


                //Esto redirige al controlador Abuelos, método Solicitudes para que la url sea correcta.
                return RedirectToAction("Solicitudes", "Abuelos");

            }
            else if (estudiante != null)
            {
                HttpContext.Session.SetInt32("id", estudiante.IdEstudiante);
                HttpContext.Session.SetString("tipo", "estudiante");
                return RedirectToAction("Busqueda", "Estudiantes");
            }
            else {
                return NotFound();
            }

            
        }
    }
}

Avus_02/Controllers/SolicitudesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Avus_02.Model;

namespace Avus_02.Controllers
{
    public class SolicitudesController : Controller
    {
        private readonly AvusContext _context;

        public SolicitudesController(AvusContext context)
        {
            _context = context;
        }

        // GET: Solicitudes
        public async Task<IActionResult> Index()
        {
            var avusContext = _context.Solicitud.Include(s => s.IdEstudianteNavigation).Include(s => s.IdHabitacionNavigation);
            return View(await avusContext.ToListAsync());
        }

        // GET: Solicitudes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var solicitud = await _context.Solicitud
                .Include(s => s.IdEstudianteNavigation)
                .Include(s => s.IdHabitacionNavigation)
                .FirstOrDefaultAsync(m => m.IdSolicitud == id);
            if (solicitud == null)
            {
                return NotFound();
            }

            return View(solicitud);
        }

        // GET: Solicitudes/Create
        public IActionResult Create()
        {
            ViewData["IdEstudiante"] = new SelectList(_context.Estudiante, "IdEstudiante", "IdEstudiante");
            ViewData["IdHabitacion"] = new SelectList(_context.Habitacion, "IdHabitacion", "IdHabitacion");
            return View();
        }

        // POST: Solicitudes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdSolicitud,FechaSolicitud,Aceptacion,FechaPrimerDia,FechaUltimoDia,IdEstudiante,IdHabitacion")] Solicitud solicitud)
        {
            if (ModelState.IsValid)
            {
                _context.Add(solicitud);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdEstudiante"] = new SelectList(_context.Estudiante, "IdEstudiante", "IdEstudiante", solicitud.IdEstudiante);
            ViewData["IdHabitacion"] = new SelectList(_context.Habitacion, "IdHabitacion", "IdHabitacion", solicitud.IdHabitacion);
            return View(solicitud);
        }

        // GET: Solicitudes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var solicitud = await _context.Solicitud.FindAsync(id);
            if (solicitud == null)
            {
                return NotFound();
            }
            ViewData["IdEstudiante"] = new SelectList(_context.Estudiante, "IdEstudiante", "IdEstudiante", solicitud.IdEstudiante);
            ViewData["IdHabitacion"] = new SelectList(_context.Habitacion, "IdHabitacion", "IdHabitacion", solicitud.IdHabitacion);
            return View(solicitud);
        }

        // POST: Solicitudes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdSolicitud,FechaSolicitud,Aceptacion,FechaPrimerDia,FechaUltimoDia,IdEstudiante,IdHabitacion")] Solicitud solicitud)
        {
            if (id != solicitud.IdSolicitud)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(solicitud);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SolicitudExists(solicitud.IdSolicitud))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdEstudiante"] = new SelectList(_context.Estudiante, "IdEstudiante", "IdEstudiante", solicitud.IdEstudiante);
            ViewData["IdHabitacion"] = new SelectList(_context.Habitacion, "IdHabitacion", "IdHabitacion", solicitud.IdHabitacion);
            return View(solicitud);
        }

        // GET: Solicitudes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var solicitud = await _context.Solicitud
                .Include(s => s.IdEstudianteNavigation)
                .Include(s => s.IdHabitacionNavigation)
                .FirstOrDefaultAsync(m => m.IdSolicitud == id);
            if (solicitud == null)
            {
                return NotFound();
            }

            return View(solicitud);
        }

        // POST: Solicitudes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var solicitud = await _context.Solicitud.FindAsync(id);
            _context.Solicitud.Remove(solicitud);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SolicitudExists(int id)
        {
            return _context.Solicitud.Any(e => e.IdSolicitud == id);
        }
    }
}

Avus_02/Views/Abuelos/Ajustes.cshtml
@{
    ViewData["Title"] = "Ajustes";
    Layout = "_LayoutAbuelo";
}

<h2>Ajustes</h2>

Avus_02/Views/Abuelos/Delete.cshtml
@model Avus_02.Model.Abuelo

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Abuelo</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Password)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Password)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Apellidos)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Apellidos)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Dni)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Dni)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Descripcion)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Nacionalidad)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Nacionalidad)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.FotoPerfil)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FotoPerfil)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.FechaNacimiento)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FechaNacimiento)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Sexo)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Sexo)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Telefono)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Telefono)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Pais)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Pais)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Comunidad)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Comunidad)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Localidad)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Localidad)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Direccion)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Direccion)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CodigoPostal)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CodigoPostal)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="IdAbuelo" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Avus_02/Views/Abuelos/FormAbuelo.cshtml
@namespace Avus_02.Model
@model SubirFoto
@{
    ViewData["Title"] = "FormAbuelo";
}

    <div>


        <nav class="navbar navbar-expand-lg navbar-dark rounded-bottom">
            <a class="navbar-brand" href="/Login/Index"><img src="~/images/logoavus.png" width="65" alt="" class=""> </a>

            <ul class="nav navbar-nav mx-auto">
                <li class="nav-item"><h1 class="nav-link " href="#">Avus</h1></li>
            </ul>

            <button class="navbar-toggler float-md-none" type="button" data-toggle="collapse"
                    data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                    aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse main-menu-item justify-content-end"
                 id="navbarSupportedContent">
                <ul class="navbar-nav align-items-center order-3 order-md-none">
                    <li class="nav-item active">
                        <a class="nav-link" href="#">Inicio</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Login" asp-action="About">Sobre Nosotros</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="#">Blog</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="#">Contacto</a>
                    </li>
                </ul>


            </div>
        </nav>
    </div>

<div class="row text-center">
    <div class="col-md-12">
        <div class="well well-sm">
            <form asp-action="Create" asp-controller="Abuelos" id="abueloForm" class="form-horizontal" enctype="multipart/form-data" method="post">
                <fieldset>
                   
                    <!--Forms con icono y input bien puesto-->
                   <div class="card mt-5">
                       <div class="form-group">
                           <div class="col-md-12 mt-5">
                               <span class="centrarTitulo">
                                   Abuelo
                               </span>
                           </div>
                       </div>
                       <div class="row">
                           <div class="col-md-1">
                           </div>
                           <span class="col-md-1 mb-2 mt-2"><i class="fa fa-user bigicon"></i></span>
                           <div class="form-group col-md-4 d-inline-block mb-2 mt-2">
                               <input id="Nombre" name="Nombre" type="text" placeholder="Nombre" class="form-control">
                           </div>
                           <div class="form-goup col-md-5 d-inline-block mb-3 mt-2">
                               <input id="Apellidos" name="Apellidos" type="text" placeholder="Apellidos"
                                      class="form-control">
                           </div>
                           <div class="col-md-1">
                           </div>
                       </div>
                       <div class="row">
                           <div class="col-md-1">
                           </div>
                           <span class="col-md-1 mb-2"><i class="fa fa-envelope-o bigicon"></i></span>
                           <div class="form-goup col-md-4 mb-3">
                               <input id="Email" name="Email" type="email" placeholder="nombre@correo.com"
                                      class="form-control">
                           </div>
                           <span class="col-md-1 col-md-offset-2 mb-2">
                               <i class="fa fa-unlock-alt bigicon"></i>
                           </span>
                           <div class="col-md-4 d-inline-block mb-3">
                               <div class="input-group">
                                   <input id="Password" name="Password" type="password" placeholder="Contraseña" class="form-control">
                                   <div class="input-group-append">
                                       <button id="show_password" class="btn btn-primary" type="button" onclick="mostrarPassword()"> <span class="fa fa-eye-slash icon"></span> </button>
                                   </div>
                               </div>
                           </div>
                           <div class="col-md-1"></div>
                       </div>

                       <div class="row">
                           <div class="col-md-1"></div>
                           <span class="col-md-1 mb-2"><i class="fa fa-id-card bigicon"></i></span>
                           <div class=" form-group col-md-4 d-inline-block mb-3">
                               <input id="Dni" name="Dni" type="text" placeholder="Documento de identidad"
                                      class="form-control">
                           </div>
                           <span class="col-md-1 mb-2"><i class="fa fa-phone-square bigicon"></i></span>
                           <div class="form-group col-md-4 d-inline-block mb-3">
                               <input id="Telefono" name="Telefono" type="text" placeholder="Ej. 615231546"
                                      class="form-control">
                           </div>
                           <div class="col-md-1"></div>
                       </div>
                       <div class="row">

                           <div class="col-md-1"></div>
                           <span class="col-md-1 mb-2"><i class="fa fa-calendar bigicon"></i></span>
                           <div class="col-md-4 d-inline-block mb-3">
                               <div class="input-group">
                                   <input placeholder="Fecha de nacimiento" class="form-control" type="text" onfocus="(this.type='date')" onblur="(this.type='text')"
                                          id="FechaNacimiento" name="FechaNacimiento" min="1900-01-01" max="2011-12-31">
                               </div>
                           </div>
                           <span class="col-md-1 mb-2">
                               <i id="offsetIcon"
                                  class="fa fa-venus-mars bigicon"></i>
                           </span>
                           <div class="col-md-4 d-inline-block mb-3">
                               <select id="Sexo" name="Sexo" type="text" class="custom-select">
                                   <option value="0" selected>Género</option>
                                   <option value="1">Hombre</option>
                                   <option value="2">Mujer</option>
                                   <option value="3">Otro</option>
                               </select>

                           </div>
                           <div class="col-md-1"></div>
                       </div>

                       <div class="row fuenteFormulario">
                           <div class="col-md-2"></div>
                           <div class=" form-group col-md-4 autocomplete">
                               <label for="Pais" class="footerEnBlanco">País</label>
                               <input id="Pais" class="form-control autocomplete" type="search" placeholder=""
                                      name="Pais" />
                           </div>
                           <div class="form-group col-md-3 autocomplete">
                               <label for="Comunidad" class="footerEnBlanco">Comunidad</label>
                               <input id="Comunidad" class="form-control autocomplete" type="search"
                                      placeholder="" name="Comunidad" />
                           </div>
                           <div class="form-group col-md-2 autocomplete">
                               <label for="Localidad" class="footerEnBlanco">Provincia</label>
                               <input id="Localidad" class="form-control autocomplete" type="search"
                                      placeholder="" name="Localidad" />
                           </div>
                           <div class="col-md-1"></div>
                       </div>
                       <div class="row ">
                           <div class="col-md-2"></div>
                           <div class="form-group col-md-2 ">
                               <label for="CodigoPostal" class="footerEnBlanco">CP</label>
                               <input id="CodigoPostal" class="form-control autocomplete" type="text"
                                      placeholder="" name="CodigoPostal" />
                           </div>
                           <div class="form-group col-md-7">
                               <label for="Direccion" class="footerEnBlanco">Dirección</label>
                               <input type="text" name="Direccion" class="form-control" id="Direccion">
                           </div>

                           <div class="col-md-1"></div>
                       </div>



                       <div class="row">
                           <div class="col-md-1"></div>

                           <span class="col-md-1 mb-2 px-xl-5 px-md-4">
                               <i class="fa fa-comment bigicon d-inline-block "></i>
                           </span>
                           <div class="col-md-9 mb-3">
                               <textarea class="form-control" id="Descripcion" name="Descripcion"
                                         placeholder="Introduce una descripción:"
                                         rows="8"></textarea>
                           </div>
                           <div class="col-md-1"></div>
                       </div>



                       <div class="form-group">
                           <div class="col-md-12 mt-3 footerEnBlanco">
                               <!-- <button type="submit" class="btn btn-primary btn-lg">Submit</button> -->
                               <input asp-for="MyImage" />
                           </div>
                       </div>
                       <div class="form-group">
                           <div class="col-md-12 mt-3">
                               <!-- <button type="submit" class="btn btn-primary btn-lg">Submit</button> -->
                               <input type="submit"  id="btnvalidar" class="btn btn-primary" value="Registrar">
                           </div>
                       </div>
                   </div>
                    
                    
                </fieldset>
            </form>
        </div>
    </div>
</div>
<script>
    FormAbuelo();
</script>
